steps:
# Step 1: Install dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

# Step 2: Build the application
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']

# Step 3: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cicd437310/my-app', '.']

# Step 4: Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'my-app', '--image', 'gcr.io/cicd437310/my-app', '--platform', 'managed', '--region', 'us-central1']

# Step 5: Deploy my.html to Google Cloud Storage
- name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli'
  args: ['gsutil', 'cp', 'my.html', 'gs://forci1234/']

images:
- 'gcr.io/cicd437310/my-app'
